/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch design system tokens
        tertiary: "#ffc174",
        "on-surface": "#dce3f1",
        "on-surface-variant": "#bdc8d1",
        "primary-fixed": "#c4e7ff",
        "surface-tint": "#7bd0ff",
        "primary-container": "#38bdf8",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-container": "#f59e0b",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004c69",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container": "#19202a",
        "surface-variant": "#2e3540",
        "inverse-on-surface": "#2a313c",
        "on-tertiary-container": "#613b00",
        "surface-container-high": "#232a35",
        primary: "#8ed5ff",
        "on-tertiary-fixed": "#2a1700",
        background: "#0d141e",
        "on-error": "#690005",
        "on-secondary": "#003824",
        "surface-container-low": "#151c26",
        "primary-fixed-dim": "#7bd0ff",
        "surface-dim": "#0d141e",
        "tertiary-fixed": "#ffddb8",
        "inverse-primary": "#00668a",
        "outline-variant": "#3e484f",
        "on-primary": "#00354a",
        secondary: "#4edea3",
        outline: "#87929a",
        "surface-bright": "#333a45",
        surface: "#0d141e",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-fixed": "#002113",
        "surface-container-highest": "#2e3540",
        "on-background": "#dce3f1",
        "inverse-surface": "#dce3f1",
        "on-primary-fixed": "#001e2c",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary": "#472a00",
        "on-primary-container": "#004965",
        "surface-container-lowest": "#080f18",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        "secondary-fixed": "#6ffbbe",
        // Existing brand and slate colors
        brand: {
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          900: '#14532d',
        },
        slate: {
          850: '#151e2e',
          950: '#0b0f19',
        }
      },
      spacing: {
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        gutter: "1rem",
        margin: "1.25rem",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "mono-body": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "mono-metric": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Geist", "sans-serif"],
        "mono-label": ["JetBrains Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "mono-body": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-metric": ["1.75rem", { lineHeight: "2rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-xl": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.025em", fontWeight: "600" }],
        "mono-label": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-md": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.005em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
