import {
  MetricsOverview,
  PRThroughputDataPoint,
  LifecycleDataPoint,
  CIReliabilityDataPoint,
  WorkflowHealthItem,
  EngineeringSignal,
  Repository,
  TrendDataPoint,
  BottleneckSummary,
  StageBaseline,
  GanttStage,
  BottleneckTraceItem,
  RiskSummary,
  RiskPRItem,
  RiskHeuristicItem,
  RepositoryHotspotItem,
  DimensionalSignalItem,
  ReleaseBlockerItem,
  ReleaseWarningItem,
  PositiveSignalItem,
  CandidatePRTraceItem,
  GitHubSyncSummary,
  ActiveSyncJob,
  SyncRepoItem,
  SyncAuditLogItem,
} from '../types';

export const mockMetricsOverview: MetricsOverview = {
  merged_prs: 142,
  merged_prs_change: '+12% vs 30d',
  open_prs: 28,
  open_prs_change: '-4% vs 30d',
  median_time_to_merge_hours: 18.4,
  median_time_change: '+4.2h vs 30d',
  build_failure_rate: 4.8,
  build_failure_rate_change: '-1.1% vs 30d',
  workflow_success_rate: 95.2,
  workflow_success_rate_change: '+1.1% vs 30d',
  release_readiness_score: 92,
  release_readiness_status: 'READY',
  release_readiness_change: 'Stable (+0%)',
  time_window_days: 30,
};

export const mockThroughputData: PRThroughputDataPoint[] = [
  { day: 'Day 1', opened: 18, merged: 15 },
  { day: 'Day 3', opened: 20, merged: 19 },
  { day: 'Day 6', opened: 22, merged: 21 },
  { day: 'Day 9', opened: 19, merged: 20 },
  { day: 'Day 12', opened: 26, merged: 23 },
  { day: 'Day 15', opened: 24, merged: 25 },
  { day: 'Day 18', opened: 22, merged: 24 },
  { day: 'Day 21', opened: 28, merged: 29 },
  { day: 'Day 24', opened: 30, merged: 31 },
  { day: 'Day 27', opened: 32, merged: 35 },
  { day: 'Day 28', opened: 34, merged: 38 },
  { day: 'Day 30', opened: 35, merged: 36 },
];

export const mockLifecycleData: LifecycleDataPoint[] = [
  { day: 'Day 1', hours: 14.2, slaTarget: 16.0 },
  { day: 'Day 4', hours: 14.6, slaTarget: 16.0 },
  { day: 'Day 8', hours: 14.9, slaTarget: 16.0 },
  { day: 'Day 11', hours: 15.1, slaTarget: 16.0 },
  { day: 'Day 14', hours: 15.5, slaTarget: 16.0 },
  { day: 'Day 18', hours: 16.3, slaTarget: 16.0 },
  { day: 'Day 21', hours: 17.2, slaTarget: 16.0 },
  { day: 'Day 25', hours: 17.9, slaTarget: 16.0 },
  { day: 'Day 28', hours: 18.2, slaTarget: 16.0 },
  { day: 'Day 30', hours: 18.4, slaTarget: 16.0 },
];

export const mockCIReliabilityData: CIReliabilityDataPoint[] = [
  { day: 'Day 1', successRate: 94.1, failureRate: 5.9 },
  { day: 'Day 4', successRate: 94.3, failureRate: 5.7 },
  { day: 'Day 8', successRate: 94.0, failureRate: 6.0 },
  { day: 'Day 11', successRate: 94.5, failureRate: 5.5 },
  { day: 'Day 14', successRate: 94.8, failureRate: 5.2 },
  { day: 'Day 18', successRate: 94.6, failureRate: 5.4 },
  { day: 'Day 21', successRate: 95.0, failureRate: 5.0 },
  { day: 'Day 25', successRate: 94.9, failureRate: 5.1 },
  { day: 'Day 28', successRate: 95.4, failureRate: 4.6 },
  { day: 'Day 30', successRate: 95.2, failureRate: 4.8 },
];

export const mockWorkflowHealth: WorkflowHealthItem[] = [
  { id: 'wf-1', name: 'integration-tests-e2e', runs: 482, failureRate: 11.4, accent: 'error' },
  { id: 'wf-2', name: 'docker-build-matrix', runs: 612, failureRate: 7.8, accent: 'tertiary' },
  { id: 'wf-3', name: 'database-migration-dryrun', runs: 189, failureRate: 6.2, accent: 'tertiary' },
  { id: 'wf-4', name: 'unit-and-lint-shard-3', runs: 1204, failureRate: 2.1, accent: 'secondary' },
  { id: 'wf-5', name: 'helm-chart-linter', runs: 355, failureRate: 0.8, accent: 'secondary' },
];

export const mockEngineeringSignals: EngineeringSignal[] = [
  {
    id: 'sig-1',
    category: 'Queue Bottleneck',
    statusBadge: 'Confidence 94%',
    title: 'Median PR lifecycle time has increased from 14.2h to 18.4h (+29.6%).',
    details: 'Review wait queue lag accounts for 68% of the aggregate delay rather than CI test pipeline duration. Team batch review rhythms recommended.',
    icon: 'hourglass_top',
    accent: 'tertiary',
    codeHighlight: '18.4h',
  },
  {
    id: 'sig-2',
    category: 'Cluster Instability',
    statusBadge: 'Severity High',
    title: 'CI failure rate increased 8% over the previous 30 days. Most recent failures are heavily concentrated in integration-tests-e2e.',
    details: 'Failure traces isolate socket timeout spikes on Redis cluster mocks running inside ephemeral Kubernetes runner nodes.',
    icon: 'error_outline',
    accent: 'error',
    codeHighlight: 'integration-tests-e2e',
  },
  {
    id: 'sig-3',
    category: 'Efficiency Gain',
    statusBadge: 'Verified',
    title: 'Build failure rate dropped to 4.8% (-1.1%), driven by enhanced Docker layer caching on Ubuntu runner pools.',
    details: 'Runner execution step time decreased by an average of 4.1 minutes per workflow invocation across base branches.',
    icon: 'speed',
    accent: 'secondary',
    codeHighlight: '4.8%',
  },
  {
    id: 'sig-4',
    category: 'Release Advisory',
    statusBadge: 'v2.4.0 Tracking',
    title: 'Release Readiness is currently at 92%. Candidate v2.4.0-rc3 is passing 4 of 5 automated gate verification checks.',
    details: 'Sole remaining gating blocker: End-to-end telemetry canary soak test currently running in staging cluster (78% elapsed).',
    icon: 'rule',
    accent: 'primary',
    codeHighlight: '92%',
  },
];

export const mockRepositories: Repository[] = [
  {
    id: 'repo-core-telemetry',
    github_id: 101,
    name: 'core-telemetry-service',
    full_name: 'org/core-telemetry-service',
    owner_login: 'org',
    is_private: true,
    default_branch: 'main',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'repo-auth-gateway',
    github_id: 102,
    name: 'auth-gateway',
    full_name: 'org/auth-gateway',
    owner_login: 'org',
    is_private: true,
    default_branch: 'main',
    created_at: '2024-02-10T00:00:00Z',
  },
  {
    id: 'repo-data-pipeline',
    github_id: 103,
    name: 'data-pipeline-runner',
    full_name: 'org/data-pipeline-runner',
    owner_login: 'org',
    is_private: true,
    default_branch: 'main',
    created_at: '2024-03-01T00:00:00Z',
  },
];

export const mockTrendDataPoints: TrendDataPoint[] = [
  { date: '2026-05-01', time_to_merge_hours: 14.2, build_failure_rate: 5.9, pr_volume: 15 },
  { date: '2026-05-05', time_to_merge_hours: 14.6, build_failure_rate: 5.7, pr_volume: 19 },
  { date: '2026-05-10', time_to_merge_hours: 15.1, build_failure_rate: 6.1, pr_volume: 21 },
  { date: '2026-05-14', time_to_merge_hours: 15.5, build_failure_rate: 5.2, pr_volume: 23 },
  { date: '2026-05-18', time_to_merge_hours: 16.3, build_failure_rate: 5.4, pr_volume: 25 },
  { date: '2026-05-21', time_to_merge_hours: 17.2, build_failure_rate: 5.0, pr_volume: 29 },
  { date: '2026-05-25', time_to_merge_hours: 17.9, build_failure_rate: 5.1, pr_volume: 31 },
  { date: '2026-05-28', time_to_merge_hours: 18.2, build_failure_rate: 4.6, pr_volume: 38 },
  { date: '2026-05-30', time_to_merge_hours: 18.4, build_failure_rate: 4.8, pr_volume: 36 },
];

/* BOTTLENECK DETECTIVE MOCKS */
export const mockBottleneckSummary: BottleneckSummary = {
  mean_lifecycle: 21.8,
  mean_lifecycle_delta: '+3.2h vs 14d baseline',
  median_duration: 18.4,
  median_duration_delta: '+4.2h vs 14d baseline',
  review_wait_median: 8.6,
  review_wait_share: 46.7,
  ci_recovery_latency: 5.4,
  ci_recovery_share: 29.5,
  merge_queue_wait: 2.1,
  merge_queue_share: 11.4,
};

export const mockStageBaselines: StageBaseline[] = [
  {
    label: 'CI Flake Recovery Target < 1.5h',
    target: '1.5h',
    actual: 'Actual: 5.4h (3.6x over SLA)',
    color: '#ffb4ab',
    isOverSla: true,
  },
  {
    label: 'Review Initial Response < 6.0h',
    target: '6.0h',
    actual: 'Actual: 8.6h (+43%)',
    color: '#ffc174',
    isOverSla: true,
  },
];

export const mockGanttStages: GanttStage[] = [
  {
    label: 'Queue Wait 7.2h (25%)',
    hours: 7.2,
    percentage: 25,
    timePoint: 'T+0.0h (PR Created)',
    color: '#ffc174',
  },
  {
    label: 'Author Rework 3.4h (12%)',
    hours: 3.4,
    percentage: 12,
    timePoint: 'T+7.2h (First Review)',
    color: '#8ed5ff',
  },
  {
    label: 'CI Stall (Flake) 9.8h (34%)',
    hours: 9.8,
    percentage: 34,
    timePoint: 'T+10.6h (Rework Pushed)',
    color: '#ffb4ab',
    isWarning: true,
  },
  {
    label: 'Re-Review Wait 6.0h (21%)',
    hours: 6.0,
    percentage: 21,
    timePoint: 'T+20.4h (Flaky Test Retry Loop)',
    color: '#ffc174',
  },
  {
    label: 'Merge Gate 1.8h (6%)',
    hours: 1.8,
    percentage: 6,
    timePoint: 'T+26.8h (Approved)',
    color: '#4edea3',
  },
];

export const mockBottleneckTraces: BottleneckTraceItem[] = [
  {
    id: 'trace-1042',
    pr_number: 1042,
    title: 'feat(auth): Ed25519 token signatures',
    branch: 'feat/ed25519-rotation',
    repository: 'org/core-telemetry-service',
    lifecycle_hours: 28.6,
    review_wait_hours: 7.2,
    ci_delay_hours: 9.8,
    ci_delay_flaky: true,
    rework_hours: 3.4,
    primary_friction_stage: 'CI Recovery [High]',
    friction_severity: 'error',
  },
  {
    id: 'trace-1039',
    pr_number: 1039,
    title: 'refactor(ingest): batch queue flush telemetry',
    branch: 'ingest/kafka-flush-opt',
    repository: 'org/core-telemetry-service',
    lifecycle_hours: 16.4,
    review_wait_hours: 11.4,
    ci_delay_hours: 0.9,
    rework_hours: 2.1,
    primary_friction_stage: 'Review Queue [Stalled]',
    friction_severity: 'warning',
  },
  {
    id: 'trace-891',
    pr_number: 891,
    title: 'fix(payment): stripe webhook idempotency lock',
    branch: 'fix/webhook-race',
    repository: 'backend/checkout-api',
    lifecycle_hours: 34.2,
    review_wait_hours: 14.5,
    ci_delay_hours: 5.4,
    rework_hours: 5.2,
    primary_friction_stage: 'Multi-Stage Stall',
    friction_severity: 'stalled',
  },
  {
    id: 'trace-1035',
    pr_number: 1035,
    title: 'chore(deps): upgrade otel collector to 0.94',
    branch: 'chore/otel-site-bump',
    repository: 'org/core-telemetry-service',
    lifecycle_hours: 4.1,
    review_wait_hours: 1.2,
    ci_delay_hours: 1.1,
    rework_hours: 0.7,
    primary_friction_stage: 'Optimal Flow',
    friction_severity: 'optimal',
  },
  {
    id: 'trace-412',
    pr_number: 412,
    title: 'docs(runbook): incident failover drill doc updates',
    branch: 'docs/drill-handbook',
    repository: 'infra/runbooks',
    lifecycle_hours: 2.5,
    review_wait_hours: 1.5,
    ci_delay_hours: 0.4,
    rework_hours: 0.2,
    primary_friction_stage: 'Optimal Flow',
    friction_severity: 'optimal',
  },
];

/* CHANGE RISK RADAR MOCKS */
export const mockRiskSummary: RiskSummary = {
  high_risk_prs: 8,
  high_risk_share: 12,
  medium_risk_prs: 24,
  medium_risk_share: 35,
  low_risk_prs: 36,
  low_risk_share: 53,
  average_risk_score: 42.6,
  average_risk_delta: '-1.4 vs 14d',
  repository_baseline: 38.2,
  sample_prs: 68,
};

export const mockRiskPRs: RiskPRItem[] = [
  {
    id: 'risk-1847',
    pr_number: 1847,
    title: 'feat(billing): split stripe idempotency webhook',
    branch: 'feat/billing-split',
    touched_time: 'touched 18m ago',
    change_size_lines: 1240,
    added_lines: 1240,
    deleted_lines: 380,
    files_count: 38,
    failure_signal: 'High (14 hotfixes)',
    failure_signal_color: 'error',
    ci_signal: 'Medium (Flake Rate)',
    ci_signal_color: 'tertiary',
    config_impact: 'High (TF/Helm)',
    config_impact_color: 'error',
    risk_score: 78,
    risk_status: 'ELEVATED SCRUTINY RECOMMENDED',
    risk_level: 'HIGH',
  },
  {
    id: 'risk-1842',
    pr_number: 1842,
    title: 'refactor(db): partition multi-tenant audit logs',
    branch: 'refactor/audit-partition',
    touched_time: 'touched 1h ago',
    change_size_lines: 890,
    added_lines: 610,
    deleted_lines: 280,
    files_count: 24,
    failure_signal: 'High',
    failure_signal_color: 'error',
    ci_signal: 'High (Flake Rate)',
    ci_signal_color: 'error',
    config_impact: 'High (Schema DDL)',
    config_impact_color: 'error',
    risk_score: 74,
    risk_status: 'ELEVATED SCRUTINY RECOMMENDED',
    risk_level: 'HIGH',
  },
  {
    id: 'risk-1839',
    pr_number: 1839,
    title: 'chore(deps): upgrade otel collector to 0.96',
    branch: 'deps/otel-upgrade',
    touched_time: 'touched 3h ago',
    change_size_lines: 310,
    added_lines: 180,
    deleted_lines: 130,
    files_count: 6,
    failure_signal: 'Low',
    failure_signal_color: 'secondary',
    ci_signal: 'Medium',
    ci_signal_color: 'tertiary',
    config_impact: 'High (Daemons)',
    config_impact_color: 'error',
    risk_score: 58,
    risk_status: 'STANDARD SCRUTINY',
    risk_level: 'MEDIUM',
  },
  {
    id: 'risk-1835',
    pr_number: 1835,
    title: 'fix(cache): add redis cluster client keepalive',
    branch: 'fix/redis-keepalive',
    touched_time: 'touched 5h ago',
    change_size_lines: 42,
    added_lines: 38,
    deleted_lines: 4,
    files_count: 2,
    failure_signal: 'Medium',
    failure_signal_color: 'tertiary',
    ci_signal: 'Optimal',
    ci_signal_color: 'secondary',
    config_impact: 'None (Pure Code)',
    config_impact_color: 'neutral',
    risk_score: 34,
    risk_status: 'NOMINAL MONITORING',
    risk_level: 'LOW',
  },
  {
    id: 'risk-1828',
    pr_number: 1828,
    title: 'feat(auth): add ed25519 jwt verification',
    branch: 'feat/ed25519-jwt',
    touched_time: 'touched 9h ago',
    change_size_lines: 450,
    added_lines: 410,
    deleted_lines: 40,
    files_count: 12,
    failure_signal: 'Low',
    failure_signal_color: 'secondary',
    ci_signal: 'Optimal',
    ci_signal_color: 'secondary',
    config_impact: 'Low (Env Var)',
    config_impact_color: 'secondary',
    risk_score: 28,
    risk_status: 'NOMINAL MONITORING',
    risk_level: 'LOW',
  },
  {
    id: 'risk-1820',
    pr_number: 1820,
    title: 'docs(runbook): update canary rollback procedure',
    branch: 'docs/canary-playbook',
    touched_time: 'touched 1d ago',
    change_size_lines: 85,
    added_lines: 65,
    deleted_lines: 20,
    files_count: 3,
    failure_signal: 'None',
    failure_signal_color: 'neutral',
    ci_signal: 'Optimal',
    ci_signal_color: 'secondary',
    config_impact: 'None (Markdown)',
    config_impact_color: 'neutral',
    risk_score: 12,
    risk_status: 'NOMINAL MONITORING',
    risk_level: 'LOW',
  },
];

export const mockRiskHeuristics: RiskHeuristicItem[] = [
  {
    id: 'rh-1',
    title: 'Large Change Volume',
    points: 22,
    description: '~1,240 / -380 lines across 38 files. Diff volume exceeds 85th percentile for this repository, increasing cognitive review load and likelihood of subtle regression.',
  },
  {
    id: 'rh-2',
    title: 'Historically Unstable File Area',
    points: 28,
    description: 'services/payment/ and billing/webhooks.go Touches files that experienced 14 rollbacks or hotfixes over the past 90 days. Failure recurrence rate in this module is 16.9%.',
  },
  {
    id: 'rh-3',
    title: 'Previous CI Flakiness in Area',
    points: 14,
    description: 'suite: test_stripe_webhook_idempotency Integration test suite flaked in 3 of the last 5 master branch runs, reducing automated test gate confidence.',
  },
  {
    id: 'rh-4',
    title: 'Deployment & Cloud Infra Modified',
    points: 14,
    description: 'k8s/payment-deployment.yaml & infra/sqs.tf Includes SQS retry policy alterations and container resource limits that modify production runtime behavior.',
  },
];

export const mockHotspots: RepositoryHotspotItem[] = [
  {
    id: 'hs-1',
    path: 'services/payment/',
    changes_count: 142,
    failures_count: 24,
    failure_rate_percent: 16.9,
    trend_label: '+4.1% (Degrading)',
    trend_status: 'degrading',
    friction_category: 'Integration Test Flakiness (Idempotency)',
  },
  {
    id: 'hs-2',
    path: 'pkg/integration/',
    changes_count: 98,
    failures_count: 18,
    failure_rate_percent: 18.4,
    trend_label: '+2.8% (Degrading)',
    trend_status: 'degrading',
    friction_category: 'Third-Party Stub Mock Timeouts',
  },
  {
    id: 'hs-3',
    path: 'infra/deployment/',
    changes_count: 64,
    failures_count: 11,
    failure_rate_percent: 17.2,
    trend_label: '-1.5% (Improving)',
    trend_status: 'improving',
    friction_category: 'Env Var Configuration & Secret Drift',
  },
  {
    id: 'hs-4',
    path: 'pkg/auth/',
    changes_count: 115,
    failures_count: 6,
    failure_rate_percent: 5.2,
    trend_label: 'Stable (±0.4%)',
    trend_status: 'stable',
    friction_category: 'Minor Token Expiry Test Skew',
  },
  {
    id: 'hs-5',
    path: 'services/notification/',
    changes_count: 52,
    failures_count: 2,
    failure_rate_percent: 3.8,
    trend_label: '-2.1% (Improving)',
    trend_status: 'improving',
    friction_category: 'Clean Build Passing Rates',
  },
];

/* RELEASE READINESS MOCKS */
export const mockDimensionalSignals: DimensionalSignalItem[] = [
  {
    id: 'ds-1',
    name: 'CI Health',
    score: 88,
    weight: 30,
    statusBadge: 'NOMINAL',
    statusColor: 'secondary',
    description: 'Automated unit & lint test suites passing at 99.4% on release candidate head.',
    targetText: 'Target: >85',
    deltaText: 'Pass (+5.4%)',
  },
  {
    id: 'ds-2',
    name: 'Change Risk',
    score: 64,
    weight: 25,
    statusBadge: 'ELEVATED RISK',
    statusColor: 'error',
    description: '2 pending PRs touch high-blast radius modules (services/payment, auth token rotation).',
    targetText: 'Target: >72',
    deltaText: 'Deficit (-11.0)',
    isDeficit: true,
  },
  {
    id: 'ds-3',
    name: 'Failure Rate',
    score: 76,
    weight: 15,
    statusBadge: 'WATCH LIST',
    statusColor: 'tertiary',
    description: '4.8% CI failure rate across staging runs over past 48h; within standard deviation but degrading.',
    targetText: 'Tolerance: <5%',
    deltaText: 'Degrading',
    isDeficit: true,
  },
  {
    id: 'ds-4',
    name: 'Stability',
    score: 89,
    weight: 10,
    statusBadge: 'STABLE',
    statusColor: 'secondary',
    description: 'No hotfix reversions or unplanned rollbacks detected across release branch commits in 7 days.',
    targetText: 'Zero Rollbacks',
    deltaText: 'Clean (0)',
  },
  {
    id: 'ds-5',
    name: 'Flakiness',
    score: 85,
    weight: 20,
    statusBadge: 'CAUTION',
    statusColor: 'tertiary',
    description: 'Flakiness detected in distributed integration test runner pool (Redis mock timeouts).',
    targetText: 'Flake Rate: 2.1%',
    deltaText: 'Elevated',
    isDeficit: true,
  },
];

export const mockReleaseBlockers: ReleaseBlockerItem[] = [
  {
    id: 'rb-1',
    category: 'PR Gate Failure',
    targetId: 'PR #1847',
    description: '1 high-risk PR pending merge (stripe idempotency webhook). Blast Radius: 78 Touched: services/billing/*',
    highlightTag: 'MUST RESOLVE',
  },
  {
    id: 'rb-2',
    category: 'CI Matrix Halt',
    targetId: 'commit 3f23cb4',
    description: '2 failed integration workflows in matrix: integration-tests-e2e-matrix. Run ID: 844921-matrix.',
    actionText: 'Inspect Run ↗',
  },
  {
    id: 'rb-3',
    category: 'Schema Sync',
    targetId: 'migration c39',
    description: '1 unresolved CI gate failure in database schema replication check (lock timeout simulator). Postgres DDL Lock',
  },
];

export const mockReleaseWarnings: ReleaseWarningItem[] = [
  {
    id: 'rw-1',
    category: 'Review Latency',
    deviationBadge: '+22% Deviation',
    description: 'Median PR lifecycle time increased 22% over baseline due to review queue congestion. Review wait: 8.6h avg',
  },
  {
    id: 'rw-2',
    category: 'Ephemeral Runners',
    deviationBadge: '11.4% Rate',
    description: 'Integration workflow failure rate elevated to 11.4% in ephemeral test clusters. Test Flake: Redis Mock ETIMEDOUT',
  },
  {
    id: 'rw-3',
    category: 'Coverage Drifts',
    deviationBadge: '2 PRs',
    description: 'Two large changes merged recently without automated synthetic smoke coverage. Telemetry Ingest pipeline module',
  },
];

export const mockPositiveSignals: PositiveSignalItem[] = [
  {
    id: 'ps-1',
    category: 'SAST & Dependencies',
    statusBadge: '100% Pass',
    description: 'No critical PR/repo security and SAST dependency vulnerability scans passing. Trivy & Snyk scan: clean',
  },
  {
    id: 'ps-2',
    category: 'Zero Incidents',
    statusBadge: '24h Window',
    description: 'No critical P0/P1 workflow failures or production alerts in the last 24 hours. Production Error Budget: 99.98%',
  },
  {
    id: 'ps-3',
    category: 'Git Sync Parity',
    statusBadge: 'In Sync',
    description: 'Release branch is synchronized with main (zero diverged or un-rebased commits). Head SHA: 7f3b0c1',
  },
  {
    id: 'ps-4',
    category: 'Cryptographic Attest',
    statusBadge: 'Signed',
    description: 'Docker Image SBOM attestation verified and signed via Cosign Keyless infrastructure. SLSA Level 3 Compliant',
  },
];

export const mockCandidateTraces: CandidatePRTraceItem[] = [
  {
    id: 'cand-1847',
    pr_number: 1847,
    title: 'feat:stripe idempotency',
    branch: 'services/billing/*',
    commit_sha: 'commit d90f21b',
    touched_subsystems: 'services/billing/*, pkg/crypto',
    risk_score: 78,
    risk_label: 'HIGH CHURN',
    ci_matrix_status: 'Failed (DB Lock)',
    ci_matrix_is_passed: false,
    security_sbom: 'Clean',
    gate_decision: 'BLOCKED',
  },
  {
    id: 'cand-1842',
    pr_number: 1842,
    title: 'fix:grpc-keepalive-window',
    branch: 'transport/grpc',
    commit_sha: 'commit 4e7a10c',
    touched_subsystems: 'transport/grpc',
    risk_score: 24,
    risk_label: 'LOW RISK',
    ci_matrix_status: '32/32 Passed',
    ci_matrix_is_passed: true,
    security_sbom: 'Clean',
    gate_decision: 'APPROVED',
  },
  {
    id: 'cand-1839',
    pr_number: 1839,
    title: 'refactor:auth-token-rotation',
    branch: 'auth/jwt',
    commit_sha: 'commit 3cdd19f',
    touched_subsystems: 'auth/jwt, middleware',
    risk_score: 58,
    risk_label: 'MEDIUM RISK',
    ci_matrix_status: 'Flaky Rerun (1)',
    ci_matrix_is_passed: true,
    security_sbom: 'Clean',
    gate_decision: 'CONDITIONAL',
  },
  {
    id: 'cand-1835',
    pr_number: 1835,
    title: 'chore:bump-opentelemetry-sdk',
    branch: 'general',
    commit_sha: 'commit 1b56cf7',
    touched_subsystems: 'general, telemetry-otel',
    risk_score: 18,
    risk_label: 'LOW RISK',
    ci_matrix_status: '32/32 Passed',
    ci_matrix_is_passed: true,
    security_sbom: 'Clean',
    gate_decision: 'APPROVED',
  },
];

/* GITHUB INTELLIGENCE SYNC MOCKS */
export const mockGitHubSyncSummary: GitHubSyncSummary = {
  active_repos: 14,
  paused_repos: 2,
  total_configured: 16,
  prs_ingested: 28492,
  prs_today: 142,
  review_threads_comments: '184.8k comments',
  workflow_runs_parsed: '318.5k',
  workflow_runs_today: '+1.2k today',
  parsing_drops: 8,
  webhook_health_rate: 99.98,
  p95_latency_ms: 320,
  request_rate_per_min: 412,
  api_quota_used: 4820,
  api_quota_total: 5000,
};

export const mockActiveSyncJob: ActiveSyncJob = {
  repo_name: 'org/core-telemetry-service',
  tier: 'Tier-0',
  description: 'Full 90-day telemetry re-index',
  current_step_name: '2. PR & Review Parsing',
  current_step_index: 2,
  progress_percent: 68,
  processed_events: 12410,
  total_events: 18250,
  eta_seconds: 42,
};

export const mockSyncRepos: SyncRepoItem[] = [
  {
    id: 'sync-1',
    name: 'core-telemetry-service',
    full_name: 'org/core-telemetry-service',
    tier: 'Tier-0',
    description: 'Ingestion backfill in progress',
    primary_branch: 'main',
    status: 'SYNCING',
    progress_percent: 68,
    last_synced: '3 mins ago',
    volume_summary: '4,120 PRs • 24.8k Commits • 68k Runs',
    webhook_status: 'Active (200 OK)',
  },
  {
    id: 'sync-2',
    name: 'auth-gateway',
    full_name: 'org/auth-gateway',
    tier: 'Tier-1',
    description: 'OAuth & Token Verification Service',
    primary_branch: 'main',
    status: 'SYNCED',
    last_synced: '12 mins ago',
    volume_summary: '1,840 PRs • 12.1k Commits • 34k Runs',
    webhook_status: 'Active (200 OK)',
  },
  {
    id: 'sync-3',
    name: 'payment-service',
    full_name: 'org/payment-service',
    tier: 'Tier-0',
    description: 'Financial Processing Ledger',
    primary_branch: 'release/v2.4',
    status: 'SYNCED',
    last_synced: '18 mins ago',
    volume_summary: '6,240 PRs • 45.9k Commits • 112k Runs',
    webhook_status: 'Active (200 OK)',
  },
  {
    id: 'sync-4',
    name: 'worker-pool',
    full_name: 'org/worker-pool',
    tier: 'Tier-2',
    description: 'Asynchronous Task Consumers',
    primary_branch: 'main',
    status: 'SYNC FAILED',
    last_synced: 'Failed 1h ago: 403 RateLimit',
    volume_summary: '912 PRs • 6.4k Commits • 18k Runs',
    webhook_status: 'Unreachable (Timeout)',
  },
  {
    id: 'sync-5',
    name: 'frontend-monorepo',
    full_name: 'org/frontend-monorepo',
    tier: 'Tier-1',
    description: 'Next.js & Shared Component Library',
    primary_branch: 'main',
    status: 'SYNCED',
    last_synced: '24 mins ago',
    volume_summary: '8,190 PRs • 61.2k Commits • 194k Runs',
    webhook_status: 'Active (200 OK)',
  },
];

export const mockSyncAuditLogs: SyncAuditLogItem[] = [
  {
    id: 'log-1',
    timestamp: '2026-05-14 10:42:15 UTC',
    repo_name: 'org/core-telemetry-service',
    trigger_type: 'Webhook: push',
    details: 'ref: refs/heads/main (7f3b0c1)',
    result_metrics: '+18 PRs, +42 Commits, +12 CI runs 14.2s',
    status_badge: 'Success [200]',
    status_type: 'success',
  },
  {
    id: 'log-2',
    timestamp: '2026-05-14 10:38:02 UTC',
    repo_name: 'org/payment-service',
    trigger_type: 'Manual: user_sync',
    details: 'triggered by: staff-lead@acme.internal',
    result_metrics: '+4 PRs, +9 Commits, +3 CI runs 4.8s',
    status_badge: 'Success [200]',
    status_type: 'success',
  },
  {
    id: 'log-3',
    timestamp: '2026-05-14 10:20:44 UTC',
    repo_name: 'org/worker-pool',
    trigger_type: 'Scheduled: daily_backfill',
    details: 'Batch queue throttled: GitHub Secondary Rate Limit',
    result_metrics: '+0 PRs (delayed retry in 60s) 1m 24s',
    status_badge: 'Warning [Rate throttled]',
    status_type: 'warning',
  },
];

